name: Reddit Crawler

on:
  workflow_dispatch:
  schedule:        
    - cron: "0 */6 * * *"
  push:
    branches:
      - '**'

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
        run: python src/Crawler/Redit/index.py