name: Reddit Crawler

on:
  workflow_dispatch:
  schedule:        
    - cron: "0 */6 * * *"
  push:
    branches:
      - '**'

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r src/Crawler/Redit/requirements.txt

      - name: Run
        run: python src/Crawler/Redit/index.py